<?php
// M3 Mobile Care Application Config & SEO Metadata
return [
  "creatorName" => "M3 Mobile Care",
  "creatorUrl" => "https://m3mobilecares.com",
  "templateName" => "M3 Mobile Care",
  "templateSuffix" => "Expert Mobile Repair & Live Service Board",
  "templateVersion" => "1.0.0",
  "templateFree" => false,
  "templateDescription" => "M3 Mobile Care - Premier smartphone repair & live diagnostic tracking center in Bangladesh. Expert screen display replacement, battery replacement, glass repair, motherboard fixing, firmware flashing, and FRP unlock.",
  "templateKeyword" => "M3 Mobile Care, Mobile Repair Bangladesh, Phone Repair Service, Display Replacement, Live Repair Tracking, Smartphone Service Center, iPhone Repair Dhaka, Samsung Glass Replacement, Battery Replacement, FRP Unlock, Phone Repair Shop Bangladesh",
  "licenseUrl" => "",
  "livePreview" => "https://m3mobilecares.com",
  "productPage" => "https://m3mobilecares.com",
  "support" => "https://m3mobilecares.com",
  "moreThemes" => "",
  "ogTitle" => "M3 Mobile Care - Expert Smartphone Repair & Live Service Board",
  "ogImage" => "https://m3mobilecares.com/assets/img/branding/logo-dark-icon.png",
  "ogType" => "website",
  "documentation" => "",
  "generator" => "",
  "changelog" => "",
  "repository" => "https://github.com/MosiurRrahman/m3-mobile-care",
  "gitRepo" => "m3-mobile-care",
  "gitRepoAccess" => "",
  "githubFreeUrl" => "",
  "facebookUrl" => "https://www.facebook.com/m3mobilecare",
  "twitterUrl" => "",
  "githubUrl" => "https://github.com/MosiurRrahman",
  "dribbbleUrl" => "",
  "instagramUrl" => ""
];
